"""Document generator module for creating documentation from repository info."""

from typing import Dict, List, Optional
from datetime import datetime
from pathlib import Path


class DocumentGenerator:
    """Generates documentation from scanned repository information."""
    
    def __init__(self, repo_info: Dict, template: str = 'default'):
        """
        Initialize the generator.
        
        Args:
            repo_info: Dictionary containing repository information
            template: Template to use for generation (default, minimal, detailed, api, readme)
        """
        self.repo_info = repo_info
        self.template_name = template
    
    def generate_and_export(self, output_path: str, format: str = 'markdown', 
                           title: Optional[str] = None, theme: str = "default",
                           markdown_flavor: str = "github", template: Optional[str] = None,
                           language: str = 'en') -> str:
        """
        Generate documentation and export to specified format.
        
        Args:
            output_path: Output file path
            format: Output format (markdown, html, txt)
            title: Document title (defaults to repository name)
            theme: Theme for HTML export (default, dark, minimal, corporate)
            markdown_flavor: Markdown flavor for markdown export (github, gitlab, commonmark)
            template: Template to use (overrides instance template)
            language: Language for documentation (en, es, fr, de, zh, ja, ar)
            
        Returns:
            Path to generated file
        """
        from accudoc.exporters import DocumentExporter
        from accudoc.doc_translator import DocumentTranslator
        
        # Generate markdown content
        content = self.generate_all(template_name=template)
        
        # Translate content if language is not English
        if language != 'en' and DocumentTranslator.is_supported(language):
            translator = DocumentTranslator(target_language=language)
            content = translator.translate_with_note(content)
        
        # Use repo name as title if not provided
        if title is None:
            title = f"{self.repo_info['name']} - Documentation"
        
        # Export to desired format
        return DocumentExporter.export(content, output_path, format=format, 
                                      title=title, theme=theme, 
                                      markdown_flavor=markdown_flavor)
        
    def generate_all(self, template_name: Optional[str] = None) -> str:
        """
        Generate all documentation sections using specified template.
        
        Args:
            template_name: Template to use (overrides instance template if provided)
        
        Returns:
            Complete documentation as a string
        """
        from accudoc.templates import TemplateManager
        
        # Use provided template or instance template
        tpl_name = template_name or self.template_name
        
        # Get template
        template_manager = TemplateManager()
        try:
            template = template_manager.get_template(tpl_name)
        except ValueError:
            # Fallback to default if template not found
            template = template_manager.get_template('default')
        
        # Generate sections based on template
        sections = []
        for section in template.get_sections():
            method_name = section['method']
            if hasattr(self, method_name):
                method = getattr(self, method_name)
                result = method()
                if result:
                    sections.append(result)
        
        return '\n\n'.join(filter(None, sections))
        
    def _generate_header(self) -> str:
        """Generate documentation header."""
        name = self.repo_info.get('name', 'Repository')
        header = [f"# {name}\n"]
        
        # Add badges if available
        badges = self.repo_info.get('badges', [])
        if badges:
            badge_line = []
            for badge in badges:
                badge_line.append(f"![{badge['label']}]({badge['url']})")
            header.append(' '.join(badge_line) + "\n")
        
        header.append(f"*Documentation generated by AccuDoc on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
        header.append("---\n")
        
        return '\n'.join(header)
        
    def _generate_overview(self) -> str:
        """Generate overview section."""
        sections = ["## Overview\n"]
        
        # Add existing README content if available
        if self.repo_info.get('readme_content'):
            sections.append("### Existing Documentation\n")
            readme = self.repo_info['readme_content']
            # Limit length if too long
            if len(readme) > 1000:
                readme = readme[:1000] + "...\n\n*(Truncated for brevity)*"
            sections.append(readme)
        else:
            sections.append(f"This repository contains the **{self.repo_info['name']}** project.")
            
        # Add git information
        git_info = self.repo_info.get('git_info', {})
        if git_info:
            sections.append("\n### Repository Information\n")
            if 'remote_url' in git_info:
                sections.append(f"- **Repository URL:** {git_info['remote_url']}")
            if 'branch' in git_info:
                sections.append(f"- **Current Branch:** {git_info['branch']}")
            
            # Show branches
            branches = git_info.get('branches', [])
            if branches:
                local_branches = [b for b in branches if not b.startswith('remotes/')]
                if local_branches:
                    sections.append(f"- **Branches:** {len(local_branches)} ({', '.join(local_branches[:5])})")
                    if len(local_branches) > 5:
                        sections.append(f"  - *...and {len(local_branches) - 5} more*")
            
            # Show tags
            tags = git_info.get('tags', [])
            if tags:
                sections.append(f"- **Tags:** {len(tags)} ({', '.join(tags[:5])})")
            
            # Show submodules
            submodules = git_info.get('submodules', [])
            if submodules:
                sections.append(f"- **Submodules:** {len(submodules)}")
                for submod in submodules[:5]:
                    sections.append(f"  - `{submod['path']}`")
                if len(submodules) > 5:
                    sections.append(f"  - *...and {len(submodules) - 5} more*")
            
            if 'last_commit' in git_info:
                sections.append(f"- **Last Commit:** {git_info['last_commit']}")
                
        return '\n'.join(sections)
        
    def _generate_features(self) -> str:
        """Generate features section."""
        sections = ["## Features\n"]
        
        features = []
        
        # Detect features based on project structure
        languages = self.repo_info.get('languages', {})
        if languages:
            features.append(f"Multi-language support: {', '.join(languages.keys())}")
            
        build_tools = self.repo_info.get('build_tools', [])
        if build_tools:
            features.append(f"Build automation with {', '.join(build_tools)}")
            
        dependencies = self.repo_info.get('dependencies', {})
        if dependencies:
            features.append(f"Dependency management for {', '.join(dependencies.keys())}")
            
        docs = self.repo_info.get('documentation', [])
        if docs:
            features.append(f"Comprehensive documentation ({len(docs)} files)")
            
        # Add scripts as features
        scripts = self.repo_info.get('scripts', {})
        if scripts.get('test'):
            features.append("Automated testing")
        if scripts.get('build'):
            features.append("Build scripts")
            
        if not features:
            return "## Features\n\n*Features will be identified as the project develops.*"
            
        for feature in features:
            sections.append(f"- {feature}")
            
        return '\n'.join(sections)
        
    def _generate_technology_stack(self) -> str:
        """Generate technology stack section."""
        sections = ["## Technology Stack\n"]
        
        # Programming languages
        languages = self.repo_info.get('languages', {})
        if languages:
            sections.append("### Programming Languages\n")
            # Sort by file count
            sorted_langs = sorted(languages.items(), key=lambda x: x[1], reverse=True)
            for lang, count in sorted_langs:
                sections.append(f"- **{lang}**: {count} files")
                
        # Dependencies and package managers
        dependencies = self.repo_info.get('dependencies', {})
        if dependencies:
            sections.append("\n### Package Managers & Dependencies\n")
            for category, files in dependencies.items():
                sections.append(f"- **{category}**")
                for file in files:
                    sections.append(f"  - `{file}`")
                    
        # Build tools
        build_tools = self.repo_info.get('build_tools', [])
        if build_tools:
            sections.append("\n### Build Tools & CI/CD\n")
            for tool in build_tools:
                sections.append(f"- {tool}")
                
        if len(sections) == 1:
            return "## Technology Stack\n\n*Technology stack information not available.*"
            
        return '\n'.join(sections)
    
    def _generate_architecture_diagram(self) -> str:
        """Generate architecture diagram section."""
        architecture = self.repo_info.get('architecture', {})
        
        if not architecture:
            return ""
        
        sections = ["## Architecture\n"]
        sections.append("### Project Structure Overview\n")
        
        # Add mermaid diagram if supported
        if architecture.get('mermaid'):
            sections.append("```mermaid")
            sections.append(architecture['mermaid'])
            sections.append("```\n")
        
        # Add text-based diagram as fallback
        if architecture.get('text'):
            sections.append("**Directory Structure:**\n")
            sections.append("```")
            sections.append(architecture['text'])
            sections.append("```")
        
        return '\n'.join(sections)
    
    def _generate_dependency_graph(self) -> str:
        """Generate dependency graph section."""
        dep_graph = self.repo_info.get('dependency_graph', {})
        
        if not dep_graph or not dep_graph.get('summary'):
            return ""
        
        sections = ["## Dependency Graph\n"]
        sections.append("### Dependency Overview\n")
        
        # Add mermaid diagram if supported
        if dep_graph.get('mermaid'):
            sections.append("```mermaid")
            sections.append(dep_graph['mermaid'])
            sections.append("```\n")
        
        # Add text-based representation
        if dep_graph.get('text'):
            sections.append("**Dependencies:**\n")
            sections.append("```")
            sections.append(dep_graph['text'])
            sections.append("```")
        
        return '\n'.join(sections)
        
    def _generate_installation(self) -> str:
        """Generate installation instructions."""
        sections = ["## Installation\n"]
        
        dependencies = self.repo_info.get('dependencies', {})
        scripts = self.repo_info.get('scripts', {})
        
        if not dependencies and not scripts.get('install'):
            sections.append("*Installation instructions will be added as the project develops.*")
            return '\n'.join(sections)
            
        sections.append("### Prerequisites\n")
        
        # Detect prerequisites based on languages
        languages = self.repo_info.get('languages', {})
        if 'Python' in languages:
            sections.append("- Python 3.7 or higher")
        if 'JavaScript' in languages or 'TypeScript' in languages:
            sections.append("- Node.js and npm (or yarn)")
        if 'Java' in languages:
            sections.append("- Java Development Kit (JDK)")
        if 'Go' in languages:
            sections.append("- Go 1.16 or higher")
        if 'Rust' in languages:
            sections.append("- Rust toolchain")
            
        sections.append("\n### Steps\n")
        
        # Clone repository
        git_info = self.repo_info.get('git_info', {})
        if git_info.get('remote_url'):
            sections.append("1. Clone the repository:")
            sections.append(f"   ```bash\n   git clone {git_info['remote_url']}\n   ```")
            sections.append(f"   ```bash\n   cd {self.repo_info['name']}\n   ```")
        else:
            sections.append("1. Navigate to the project directory")
            
        # Install dependencies
        step_num = 2
        if 'Python' in dependencies:
            sections.append(f"\n{step_num}. Install Python dependencies:")
            if 'requirements.txt' in dependencies['Python']:
                sections.append("   ```bash\n   pip install -r requirements.txt\n   ```")
            elif 'Pipfile' in dependencies['Python']:
                sections.append("   ```bash\n   pipenv install\n   ```")
            elif 'pyproject.toml' in dependencies['Python']:
                sections.append("   ```bash\n   pip install -e .\n   ```")
            step_num += 1
            
        if 'JavaScript/Node' in dependencies:
            sections.append(f"\n{step_num}. Install Node.js dependencies:")
            sections.append("   ```bash\n   npm install\n   ```")
            sections.append("   *or if using yarn:*")
            sections.append("   ```bash\n   yarn install\n   ```")
            step_num += 1
            
        if 'Go' in dependencies:
            sections.append(f"\n{step_num}. Install Go dependencies:")
            sections.append("   ```bash\n   go mod download\n   ```")
            step_num += 1
            
        if 'Rust' in dependencies:
            sections.append(f"\n{step_num}. Build the project:")
            sections.append("   ```bash\n   cargo build\n   ```")
            step_num += 1
            
        # Custom install scripts
        if scripts.get('install'):
            sections.append(f"\n{step_num}. Run installation scripts:")
            for script in scripts['install']:
                sections.append(f"   ```bash\n   {script}\n   ```")
                
        return '\n'.join(sections)
        
    def _generate_usage(self) -> str:
        """Generate usage/launch instructions."""
        sections = ["## Usage\n"]
        
        scripts = self.repo_info.get('scripts', {})
        languages = self.repo_info.get('languages', {})
        
        # Run scripts
        if scripts.get('run'):
            sections.append("### Running the Application\n")
            for script in scripts['run']:
                sections.append(f"```bash\n{script}\n```")
                
        elif scripts.get('build'):
            sections.append("### Building the Application\n")
            for script in scripts['build']:
                sections.append(f"```bash\n{script}\n```")
                
        # Generic instructions based on language
        elif languages:
            sections.append("### Running the Application\n")
            if 'Python' in languages:
                sections.append("For Python projects:")
                sections.append("```bash\npython main.py\n```")
                sections.append("*or*")
                sections.append("```bash\npython -m <module_name>\n```")
            if 'JavaScript' in languages or 'TypeScript' in languages:
                sections.append("\nFor Node.js projects:")
                sections.append("```bash\nnode index.js\n```")
                sections.append("*or*")
                sections.append("```bash\nnpm start\n```")
            if 'Go' in languages:
                sections.append("\nFor Go projects:")
                sections.append("```bash\ngo run main.go\n```")
            if 'Rust' in languages:
                sections.append("\nFor Rust projects:")
                sections.append("```bash\ncargo run\n```")
                
        # Testing
        if scripts.get('test'):
            sections.append("\n### Running Tests\n")
            for script in scripts['test']:
                sections.append(f"```bash\n{script}\n```")
                
        if len(sections) == 1:
            sections.append("*Usage instructions will be added as the project develops.*")
            
        return '\n'.join(sections)
        
    def _generate_project_structure(self) -> str:
        """Generate project structure section."""
        sections = ["## Project Structure\n"]
        
        files = self.repo_info.get('files', [])
        if not files:
            return "## Project Structure\n\n*Project structure information not available.*"
            
        sections.append("```")
        
        # Create a tree-like structure
        tree = {}
        for file in files[:50]:  # Limit to first 50 files
            parts = file.split('/')
            current = tree
            for part in parts:
                if part not in current:
                    current[part] = {}
                current = current[part]
                
        def print_tree(node, prefix="", is_last=True):
            items = list(node.keys())
            result = []
            for i, item in enumerate(items):
                is_last_item = i == len(items) - 1
                connector = "└── " if is_last_item else "├── "
                result.append(f"{prefix}{connector}{item}")
                
                if node[item]:  # Has children
                    extension = "    " if is_last_item else "│   "
                    result.extend(print_tree(node[item], prefix + extension, is_last_item))
            return result
            
        tree_lines = print_tree(tree)
        sections.extend(tree_lines[:100])  # Limit output
        
        if len(files) > 50:
            sections.append(f"\n... and {len(files) - 50} more files")
            
        sections.append("```")
        
        # Documentation files
        docs = self.repo_info.get('documentation', [])
        if docs:
            sections.append("\n### Key Documentation Files\n")
            for doc in docs[:10]:
                sections.append(f"- `{doc}`")
                
        return '\n'.join(sections)
        
    def _generate_license_section(self) -> str:
        """Generate license section."""
        license_info = self.repo_info.get('license')
        
        if license_info:
            return f"## License\n\nThis project is licensed under the **{license_info}**."
        else:
            return "## License\n\n*License information not found.*"
    
    def _generate_changelog(self) -> str:
        """Generate changelog from git commits."""
        git_info = self.repo_info.get('git_info', {})
        commits = git_info.get('recent_commits', [])
        
        if not commits:
            return "## Changelog\n\n*No git history available.*"
        
        sections = ["## Changelog\n"]
        sections.append("Recent changes to this repository:\n")
        
        # Group commits by date
        from collections import defaultdict
        commits_by_date = defaultdict(list)
        for commit in commits:
            commits_by_date[commit['date']].append(commit)
        
        # Generate changelog entries
        for date in sorted(commits_by_date.keys(), reverse=True):
            sections.append(f"\n### {date}\n")
            for commit in commits_by_date[date]:
                sections.append(f"- **{commit['hash']}** {commit['message']} (*{commit['author']}*)")
        
        return '\n'.join(sections)
    
    def _generate_contributors(self) -> str:
        """Generate contributors section from git history."""
        git_info = self.repo_info.get('git_info', {})
        contributors = git_info.get('contributors', [])
        
        if not contributors:
            return "## Contributors\n\n*No git history available.*"
        
        sections = ["## Contributors\n"]
        sections.append("Thank you to all the contributors who have helped build this project:\n")
        
        for contributor in contributors:
            sections.append(f"- **{contributor['name']}** ({contributor['commits']} commits)")
        
        return '\n'.join(sections)
    
    def _generate_api_documentation(self) -> str:
        """Generate API documentation section."""
        api_docs = self.repo_info.get('api_docs', {})
        
        if not api_docs or not any(api_docs.values()):
            return ""
        
        sections = ["## API Documentation\n"]
        
        # Document classes
        classes = api_docs.get('classes', [])
        if classes:
            sections.append("### Classes\n")
            for cls in classes[:10]:  # Limit to 10
                sections.append(f"#### `{cls['name']}`")
                sections.append(f"*Defined in: `{cls['file']}` (line {cls['line']})*\n")
                if cls.get('docstring'):
                    sections.append(cls['docstring'] + "\n")
                else:
                    sections.append("*No documentation available*\n")
        
        # Document functions
        functions = api_docs.get('functions', [])
        if functions:
            sections.append("### Functions\n")
            for func in functions[:15]:  # Limit to 15
                params = func['params'] if func['params'] else ''
                sections.append(f"#### `{func['name']}({params})`")
                sections.append(f"*Defined in: `{func['file']}` (line {func['line']})*\n")
                if func.get('docstring'):
                    sections.append(func['docstring'] + "\n")
                else:
                    sections.append("*No documentation available*\n")
        
        # Document methods (only if not too many)
        methods = api_docs.get('methods', [])
        if methods and len(methods) <= 20:
            sections.append("### Methods\n")
            for method in methods[:20]:  # Limit to 20
                class_name = method.get('class', 'Unknown')
                params = method['params'] if method['params'] else ''
                sections.append(f"#### `{class_name}.{method['name']}({params})`")
                sections.append(f"*Defined in: `{method['file']}` (line {method['line']})*\n")
                if method.get('docstring'):
                    sections.append(method['docstring'] + "\n")
                else:
                    sections.append("*No documentation available*\n")
        
        return '\n'.join(sections)
    
    def _generate_code_examples(self) -> str:
        """Generate code examples section."""
        examples = self.repo_info.get('code_examples', [])
        
        if not examples:
            return ""
        
        sections = ["## Code Examples\n"]
        sections.append("The repository includes the following code examples:\n")
        
        for example in examples[:10]:  # Limit to 10 examples
            sections.append(f"### {example['name']}\n")
            sections.append(f"*Location: `{example['file']}`*\n")
            if example.get('description'):
                sections.append(example['description'] + "\n")
            
            if example.get('preview'):
                lang = example.get('language', '')
                sections.append(f"```{lang}")
                sections.append(example['preview'])
                sections.append("```\n")
        
        return '\n'.join(sections)
    
    def _generate_code_statistics(self) -> str:
        """Generate detailed code statistics section."""
        code_stats = self.repo_info.get('code_stats', {})
        
        if not code_stats or code_stats.get('total_lines', 0) == 0:
            return ""
        
        sections = ["## Code Statistics\n"]
        
        # Overall statistics
        sections.append("### Overall Statistics\n")
        sections.append(f"- **Total Lines:** {code_stats['total_lines']:,}")
        sections.append(f"- **Code Lines:** {code_stats['code_lines']:,}")
        sections.append(f"- **Comment Lines:** {code_stats['comment_lines']:,}")
        sections.append(f"- **Blank Lines:** {code_stats['blank_lines']:,}")
        sections.append(f"- **Files Analyzed:** {code_stats['file_count']}")
        
        # Calculate percentages
        total = code_stats['total_lines']
        if total > 0:
            code_pct = (code_stats['code_lines'] / total) * 100
            comment_pct = (code_stats['comment_lines'] / total) * 100
            blank_pct = (code_stats['blank_lines'] / total) * 100
            sections.append(f"\n**Code Distribution:**")
            sections.append(f"- Code: {code_pct:.1f}%")
            sections.append(f"- Comments: {comment_pct:.1f}%")
            sections.append(f"- Blank: {blank_pct:.1f}%")
        
        # Per-language statistics
        by_language = code_stats.get('by_language', {})
        if by_language:
            sections.append("\n### Statistics by Language\n")
            sections.append("| Language | Files | Total Lines | Code Lines | Comment Lines |")
            sections.append("|----------|-------|-------------|------------|---------------|")
            
            for lang in sorted(by_language.keys()):
                stats = by_language[lang]
                sections.append(
                    f"| {lang} | {stats['files']} | {stats['total_lines']:,} | "
                    f"{stats['code_lines']:,} | {stats['comment_lines']:,} |"
                )
        
        return '\n'.join(sections)
    
    def _generate_todos(self) -> str:
        """Generate TODO/FIXME section."""
        todos = self.repo_info.get('todos', [])
        
        if not todos:
            return ""
        
        sections = ["## Development Notes\n"]
        sections.append("The following TODO items and notes were found in the codebase:\n")
        
        # Group by type
        from collections import defaultdict
        by_type = defaultdict(list)
        for todo in todos:
            by_type[todo['type']].append(todo)
        
        for todo_type in ['TODO', 'FIXME', 'BUG', 'HACK', 'XXX', 'NOTE']:
            items = by_type.get(todo_type, [])
            if items:
                sections.append(f"\n### {todo_type} ({len(items)})\n")
                for item in items[:20]:  # Limit to 20 per type
                    sections.append(f"- `{item['file']}:{item['line']}` - {item['message']}")
        
        if len(todos) > 100:
            sections.append(f"\n*... and {len(todos) - 100} more items*")
        
        return '\n'.join(sections)
    
    def _generate_frameworks(self) -> str:
        """Generate frameworks section."""
        frameworks = self.repo_info.get('frameworks', [])
        
        if not frameworks:
            return ""
        
        sections = ["## Frameworks & Libraries\n"]
        sections.append("The following frameworks and libraries were detected:\n")
        
        # Group by confidence
        high_confidence = [f for f in frameworks if f['confidence'] == 'high']
        medium_confidence = [f for f in frameworks if f['confidence'] == 'medium']
        
        if high_confidence:
            sections.append("### Primary Frameworks\n")
            for framework in high_confidence:
                sections.append(f"- **{framework['name']}** - {framework['evidence']}")
        
        if medium_confidence:
            sections.append("\n### Additional Technologies\n")
            for framework in medium_confidence:
                sections.append(f"- {framework['name']} - {framework['evidence']}")
        
        return '\n'.join(sections)
    
    def _generate_configuration_files(self) -> str:
        """Generate configuration files section."""
        config_files = self.repo_info.get('config_files', {})
        
        if not config_files or not any(config_files.values()):
            return ""
        
        sections = ["## Configuration Files\n"]
        sections.append("The project uses the following configuration files:\n")
        
        for config_type, files in config_files.items():
            if files:
                sections.append(f"\n### {config_type.upper()} Files\n")
                for file_info in files[:10]:  # Limit to 10 per type
                    sections.append(f"- `{file_info['file']}`")
                    if file_info.get('keys'):
                        sections.append(f"  - Configuration keys: {', '.join(file_info['keys'][:5])}")
                        if len(file_info['keys']) > 5:
                            sections.append(f"  - ...and {len(file_info['keys']) - 5} more")
        
        return '\n'.join(sections)
    
    def _generate_environment_variables(self) -> str:
        """Generate environment variables section."""
        env_vars = self.repo_info.get('env_vars', [])
        
        if not env_vars:
            return ""
        
        sections = ["## Environment Variables\n"]
        sections.append("The following environment variables are used by this project:\n")
        
        # Group by type
        definitions = [v for v in env_vars if v['type'] == 'definition']
        usages = [v for v in env_vars if v['type'] == 'usage']
        
        if definitions:
            sections.append("\n### Defined Variables\n")
            sections.append("These variables are defined in configuration files:\n")
            for var in definitions[:20]:  # Limit
                sections.append(f"- `{var['name']}` (from `{var['source']}`)")
        
        if usages:
            sections.append("\n### Used Variables\n")
            sections.append("These variables are referenced in the code:\n")
            for var in usages[:20]:  # Limit
                sections.append(f"- `{var['name']}` (used in `{var['source']}`)")
        
        if len(env_vars) > 40:
            sections.append(f"\n*...and {len(env_vars) - 40} more environment variables*")
        
        return '\n'.join(sections)
    
    def _generate_type_information(self) -> str:
        """Generate type information section."""
        type_info = self.repo_info.get('type_info', {})
        
        if not type_info or not any(type_info.values()):
            return ""
        
        sections = ["## Type Information\n"]
        sections.append("The project uses static typing:\n")
        
        # Python typed functions
        python_funcs = type_info.get('python_typed_functions', [])
        if python_funcs:
            sections.append(f"\n### Python Type Hints\n")
            sections.append(f"Found {len(python_funcs)} typed functions:\n")
            for func in python_funcs[:10]:
                sections.append(f"- `{func['name']}() -> {func['return_type']}` in `{func['file']}`")
            if len(python_funcs) > 10:
                sections.append(f"- *...and {len(python_funcs) - 10} more*")
        
        # TypeScript interfaces
        ts_interfaces = type_info.get('typescript_interfaces', [])
        if ts_interfaces:
            sections.append(f"\n### TypeScript Interfaces\n")
            sections.append(f"Found {len(ts_interfaces)} interfaces:\n")
            for interface in ts_interfaces[:10]:
                sections.append(f"- `{interface['name']}` in `{interface['file']}`")
            if len(ts_interfaces) > 10:
                sections.append(f"- *...and {len(ts_interfaces) - 10} more*")
        
        # TypeScript types
        ts_types = type_info.get('typescript_types', [])
        if ts_types:
            sections.append(f"\n### TypeScript Type Aliases\n")
            sections.append(f"Found {len(ts_types)} type aliases:\n")
            for type_alias in ts_types[:10]:
                sections.append(f"- `{type_alias['name']}` in `{type_alias['file']}`")
            if len(ts_types) > 10:
                sections.append(f"- *...and {len(ts_types) - 10} more*")
        
        return '\n'.join(sections)
    
    def _generate_import_analysis(self) -> str:
        """Generate import analysis section."""
        imports = self.repo_info.get('imports', {})
        
        if not imports or not any(imports.values()):
            return ""
        
        sections = ["## Import Analysis\n"]
        sections.append("Analysis of module and package imports:\n")
        
        for lang, lang_imports in imports.items():
            if lang_imports:
                lang_name = lang.capitalize()
                sections.append(f"\n### {lang_name} Imports\n")
                sections.append(f"Most frequently imported modules:\n")
                
                # Show top imports
                sorted_imports = sorted(lang_imports.items(), key=lambda x: x[1], reverse=True)[:15]
                for module, count in sorted_imports:
                    sections.append(f"- `{module}` ({count} times)")
        
        return '\n'.join(sections)
    
    def _generate_student_info(self) -> str:
        """Generate student/academic information section."""
        return """## Student Information

**Project Title:** [Your Project Title]  
**Student Name:** [Your Name]  
**Student ID:** [Your ID]  
**Course:** [Course Name/Number]  
**Instructor:** [Instructor Name]  
**Date:** [Submission Date]  
**Institution:** [University/College Name]
"""
    
    def _generate_learning_objectives(self) -> str:
        """Generate learning objectives section."""
        # Try to infer learning objectives from project type
        languages = self.repo_info.get('languages', {})
        frameworks = self.repo_info.get('frameworks', [])
        
        objectives = []
        
        if languages:
            primary_langs = list(languages.keys())[:3]
            objectives.append(f"Demonstrate proficiency in {', '.join(primary_langs)}")
        
        if frameworks:
            objectives.append(f"Apply {', '.join(frameworks[:2])} framework(s) in a real-world project")
        
        objectives.append("Practice software development best practices")
        objectives.append("Implement version control using Git")
        objectives.append("Create clear and comprehensive documentation")
        
        content = "## Learning Objectives\n\n"
        content += "This project demonstrates the following learning outcomes:\n\n"
        
        for i, obj in enumerate(objectives, 1):
            content += f"{i}. {obj}\n"
        
        content += "\n*Note: Update these objectives based on your course requirements.*\n"
        
        return content
    
    def _generate_assignment_requirements(self) -> str:
        """Generate assignment requirements section."""
        return """## Assignment Requirements

### Functional Requirements

- [ ] Requirement 1: [Describe the main functionality]
- [ ] Requirement 2: [Additional features]
- [ ] Requirement 3: [User interface elements]
- [ ] Requirement 4: [Data handling/storage]

### Technical Requirements

- [ ] Code must be well-structured and follow best practices
- [ ] Include error handling and input validation
- [ ] Write unit tests for core functionality
- [ ] Document all functions and classes
- [ ] Use version control (Git) throughout development

### Documentation Requirements

- [ ] README with setup and usage instructions
- [ ] Code comments for complex logic
- [ ] User guide or tutorial
- [ ] Technical documentation

*Update this section with your specific assignment requirements.*
"""
    
    def _generate_testing_section(self) -> str:
        """Generate testing section for student projects."""
        # Check if tests exist
        files = self.repo_info.get('files', [])
        has_tests = any('test' in f.lower() for f in files)
        
        content = "## Testing\n\n"
        
        if has_tests:
            content += "This project includes automated tests.\n\n"
            content += "### Running Tests\n\n"
            
            # Detect test framework
            languages = self.repo_info.get('languages', {})
            if 'Python' in languages:
                content += "```bash\npython -m pytest\n# or\npython -m unittest discover\n```\n\n"
            elif 'JavaScript' in languages or 'TypeScript' in languages:
                content += "```bash\nnpm test\n```\n\n"
            elif 'Java' in languages:
                content += "```bash\nmvn test\n# or\n./gradlew test\n```\n\n"
            
            content += "### Test Coverage\n\n"
            content += "Aim for at least 70% code coverage in your tests.\n\n"
        else:
            content += "### Test Plan\n\n"
            content += "Describe how you tested your project:\n\n"
            content += "1. **Unit Tests**: List unit tests performed\n"
            content += "2. **Integration Tests**: Describe integration test scenarios\n"
            content += "3. **Manual Testing**: Document manual test cases\n"
            content += "4. **Edge Cases**: List edge cases tested\n\n"
        
        content += "### Known Issues\n\n"
        content += "List any known bugs or limitations:\n\n"
        content += "- Issue 1: [Description]\n"
        content += "- Issue 2: [Description]\n"
        
        return content
    
    def _generate_deliverables(self) -> str:
        """Generate deliverables section."""
        return """## Deliverables

This project submission includes:

### Code Deliverables
- [ ] Source code files
- [ ] Configuration files
- [ ] Build/dependency files
- [ ] Test files

### Documentation Deliverables
- [ ] This README file
- [ ] Code documentation/comments
- [ ] User guide or tutorial
- [ ] API documentation (if applicable)

### Additional Deliverables
- [ ] Presentation slides (if required)
- [ ] Demo video (if required)
- [ ] Project report (if required)
- [ ] Reflection/learning log (if required)

*Check your assignment rubric for specific deliverable requirements.*
"""
    
    def _generate_resources(self) -> str:
        """Generate resources and references section."""
        return """## Resources and References

### Documentation
- [Official Documentation Links]
- [Tutorial Resources]
- [API References]

### Libraries and Tools
- List key libraries used
- Development tools
- Testing frameworks

### Learning Resources
- Online tutorials followed
- Stack Overflow solutions referenced
- Academic papers or textbooks

### Acknowledgments
- Third-party code or libraries used
- Tutorials or guides that helped
- Classmates or mentors consulted (with their permission)

*Remember to properly cite all resources according to academic integrity policies.*
"""
    
    def _generate_acknowledgments(self) -> str:
        """Generate acknowledgments section."""
        return """## Acknowledgments

I would like to thank:

- **Instructor**: [Name] - For guidance and course instruction
- **Teaching Assistants**: [Names] - For help during office hours
- **Classmates**: [Names] - For collaboration and discussion (where permitted)
- **Open Source Community**: For the libraries and tools that made this project possible

*Add specific acknowledgments relevant to your project.*
"""
            
    def _generate_footer(self) -> str:
        """Generate documentation footer."""
        return """---

*This documentation was automatically generated by [AccuDoc](https://github.com/jamesellette/AccuDoc).*

*Please verify all information and update as needed.*"""
