"""
ReadTheDocs integration module for AccuDoc.

Generates Sphinx-compatible documentation projects that can be published
to ReadTheDocs or built locally with Sphinx.
"""

from pathlib import Path
from typing import Optional, Dict
import datetime


class ReadTheDocsGenerator:
    """Generate Sphinx/ReadTheDocs-compatible documentation."""
    
    def __init__(self, project_name: str, author: str = "AccuDoc",
                 version: str = "1.0", theme: str = "sphinx_rtd_theme"):
        """
        Initialize ReadTheDocs generator.
        
        Args:
            project_name: Name of the project
            author: Author name
            version: Project version
            theme: Sphinx theme to use
        """
        self.project_name = project_name
        self.author = author
        self.version = version
        self.theme = theme
        self.extensions = [
            'sphinx.ext.autodoc',
            'sphinx.ext.viewcode',
            'sphinx.ext.napoleon',
            'sphinx.ext.intersphinx',
        ]
    
    def generate_sphinx_project(self, output_dir: Path, documentation: str) -> Path:
        """
        Generate a complete Sphinx project structure.
        
        Args:
            output_dir: Directory to create Sphinx project in
            documentation: Markdown documentation content
            
        Returns:
            Path to generated Sphinx project
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create source directory
        source_dir = output_dir / 'source'
        source_dir.mkdir(exist_ok=True)
        
        # Create _static and _templates directories
        (source_dir / '_static').mkdir(exist_ok=True)
        (source_dir / '_templates').mkdir(exist_ok=True)
        
        # Generate conf.py
        self._generate_conf_py(source_dir)
        
        # Convert markdown to RST and save as index.rst
        self._generate_index_rst(source_dir, documentation)
        
        # Generate Makefile
        self._generate_makefile(output_dir)
        
        # Generate make.bat for Windows
        self._generate_make_bat(output_dir)
        
        # Generate requirements.txt
        self._generate_requirements(output_dir)
        
        # Generate .readthedocs.yaml
        self._generate_rtd_config(output_dir)
        
        return output_dir
    
    def _generate_conf_py(self, source_dir: Path):
        """Generate Sphinx configuration file."""
        conf_content = f'''# Configuration file for the Sphinx documentation builder.
# Generated by AccuDoc

import os
import sys

# Project information
project = '{self.project_name}'
copyright = '{datetime.datetime.now().year}, {self.author}'
author = '{self.author}'
version = '{self.version}'
release = '{self.version}'

# General configuration
extensions = {self.extensions}

# Add any paths that contain templates here
templates_path = ['_templates']

# List of patterns to exclude
exclude_patterns = []

# HTML output options
html_theme = '{self.theme}'
html_static_path = ['_static']

# Theme options
html_theme_options = {{
    'navigation_depth': 4,
}}

# Napoleon settings (for Google/NumPy style docstrings)
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True

# Intersphinx mapping
intersphinx_mapping = {{
    'python': ('https://docs.python.org/3', None),
}}

# Master document
master_doc = 'index'

# Syntax highlighting
pygments_style = 'sphinx'
'''
        
        conf_path = source_dir / 'conf.py'
        conf_path.write_text(conf_content, encoding='utf-8')
    
    def _generate_index_rst(self, source_dir: Path, documentation: str):
        """Generate index.rst from markdown documentation."""
        from accudoc.exporters import ReStructuredTextExporter
        
        exporter = ReStructuredTextExporter()
        
        # Add a proper Sphinx index structure
        rst_header = f'''{self.project_name}
{'=' * len(self.project_name)}

.. toctree::
   :maxdepth: 2
   :caption: Contents:

'''
        
        # Convert markdown to RST
        rst_content = exporter._markdown_to_rst(documentation)
        
        # Combine header and content
        full_rst = rst_header + '\n' + rst_content
        
        # Add indices section at the end
        full_rst += '''

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
'''
        
        index_path = source_dir / 'index.rst'
        index_path.write_text(full_rst, encoding='utf-8')
    
    def _generate_makefile(self, output_dir: Path):
        """Generate Makefile for building documentation."""
        makefile_content = '''# Makefile for Sphinx documentation
#

SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
\t@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
\t@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
'''
        
        makefile_path = output_dir / 'Makefile'
        makefile_path.write_text(makefile_content, encoding='utf-8')
    
    def _generate_make_bat(self, output_dir: Path):
        """Generate make.bat for Windows."""
        make_bat_content = '''@ECHO OFF

pushd %~dp0

REM Command file for Sphinx documentation

if "%SPHINXBUILD%" == "" (
\tset SPHINXBUILD=sphinx-build
)
set SOURCEDIR=source
set BUILDDIR=build

if "%1" == "" goto help

%SPHINXBUILD% >NUL 2>NUL
if errorlevel 9009 (
\techo.
\techo.The 'sphinx-build' command was not found. Make sure you have Sphinx
\techo.installed, then set the SPHINXBUILD environment variable to point
\techo.to the full path of the 'sphinx-build' executable. Alternatively you
\techo.may add the Sphinx directory to PATH.
\techo.
\techo.If you don't have Sphinx installed, grab it from
\techo.https://www.sphinx-doc.org/
\texit /b 1
)

%SPHINXBUILD% -M %1 %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%
goto end

:help
%SPHINXBUILD% -M help %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%

:end
popd
'''
        
        make_bat_path = output_dir / 'make.bat'
        make_bat_path.write_text(make_bat_content, encoding='utf-8')
    
    def _generate_requirements(self, output_dir: Path):
        """Generate requirements.txt for Sphinx."""
        requirements_content = f'''sphinx>=4.0.0
{self.theme}
sphinx-autodoc-typehints
'''
        
        req_path = output_dir / 'requirements.txt'
        req_path.write_text(requirements_content, encoding='utf-8')
    
    def _generate_rtd_config(self, output_dir: Path):
        """Generate .readthedocs.yaml configuration."""
        rtd_config = f'''# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: source/conf.py

# Build documentation with MkDocs (alternative)
#mkdocs:
#  configuration: mkdocs.yml

# Python version and requirements
python:
  version: "3.9"
  install:
    - requirements: requirements.txt

# Build formats
formats:
  - pdf
  - epub
'''
        
        rtd_path = output_dir / '.readthedocs.yaml'
        rtd_path.write_text(rtd_config, encoding='utf-8')


def generate_readthedocs_project(repo_info: Dict, output_dir: str,
                                 documentation: str) -> Path:
    """
    Convenience function to generate ReadTheDocs project.
    
    Args:
        repo_info: Repository information dictionary
        output_dir: Output directory path
        documentation: Markdown documentation content
        
    Returns:
        Path to generated Sphinx project
    """
    project_name = repo_info.get('name', 'Documentation')
    version = repo_info.get('git_info', {}).get('version', '1.0')
    
    generator = ReadTheDocsGenerator(
        project_name=project_name,
        author='AccuDoc',
        version=version,
        theme='sphinx_rtd_theme'
    )
    
    return generator.generate_sphinx_project(Path(output_dir), documentation)
