"""
Spell checker module for AccuDoc.

Provides spell checking functionality for documentation files
using a simple dictionary-based approach with common programming
terms and technical vocabulary.
"""

import re
import logging
from typing import Dict, List, Set, Tuple, Optional, Any
from pathlib import Path
from collections import defaultdict


class SpellChecker:
    """Simple spell checker for documentation."""
    
    # Common technical and programming terms that should be considered correct
    TECHNICAL_TERMS = {
        # Programming languages
        'python', 'javascript', 'typescript', 'java', 'cpp', 'csharp',
        'golang', 'rust', 'ruby', 'php', 'kotlin', 'swift', 'scala',
        # Frameworks and libraries
        'django', 'flask', 'react', 'angular', 'vue', 'nodejs', 'express',
        'spring', 'tensorflow', 'pytorch', 'pandas', 'numpy', 'matplotlib',
        # Tools and technologies
        'github', 'gitlab', 'bitbucket', 'docker', 'kubernetes', 'git',
        'jenkins', 'travis', 'circleci', 'webpack', 'babel', 'eslint',
        'pytest', 'junit', 'mocha', 'jest', 'selenium', 'cypress',
        # File formats and protocols
        'json', 'yaml', 'xml', 'html', 'css', 'svg', 'pdf', 'http',
        'https', 'ssh', 'ftp', 'smtp', 'tcp', 'udp', 'websocket',
        # Development concepts
        'api', 'rest', 'graphql', 'crud', 'mvc', 'mvvm', 'orm', 'sdk',
        'cli', 'gui', 'ide', 'repo', 'repos', 'async', 'await', 'cicd',
        'devops', 'agile', 'scrum', 'kanban', 'tdd', 'bdd', 'regex',
        # Cloud and databases
        'aws', 'azure', 'gcp', 'mysql', 'postgresql', 'mongodb', 'redis',
        'elasticsearch', 'sqlite', 'nosql', 'sql', 'db', 'cdn',
        # Package managers
        'npm', 'pip', 'yarn', 'maven', 'gradle', 'cargo', 'composer',
        # Common abbreviations
        'etc', 'eg', 'ie', 'vs', 'aka', 'url', 'uri', 'uuid', 'ascii',
        'utf', 'unicode', 'oauth', 'jwt', 'ssl', 'tls', 'ipv4', 'ipv6',
        # Documentation terms
        'readme', 'changelog', 'todo', 'fixme', 'docstring', 'markdown',
        # AccuDoc specific
        'accudoc', 'autodoc', 'autogenerated', 'monorepo', 'submodule',
        # Common code terms
        'bool', 'int', 'str', 'dict', 'list', 'tuple', 'var', 'const',
        'func', 'def', 'class', 'struct', 'enum', 'namespace', 'config',
        'configs', 'stdin', 'stdout', 'stderr', 'env', 'ctx', 'args',
        'kwargs', 'param', 'params', 'auth', 'init', 'util', 'utils',
        'dir', 'dirs', 'filepath', 'filename', 'basename', 'dirname',
    }
    
    # Common English words (simplified dictionary)
    COMMON_WORDS = {
        'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it',
        'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this',
        'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or',
        'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
        'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
        'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know',
        'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could',
        'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only', 'come',
        'its', 'over', 'think', 'also', 'back', 'after', 'use', 'two', 'how',
        'our', 'work', 'first', 'well', 'way', 'even', 'new', 'want', 'because',
        'any', 'these', 'give', 'day', 'most', 'us', 'is', 'was', 'are', 'been',
        'has', 'had', 'were', 'said', 'did', 'having', 'may', 'should', 'might',
        # Documentation specific words
        'documentation', 'document', 'documents', 'documented', 'documenting',
        'generate', 'generates', 'generated', 'generating', 'generator',
        'install', 'installation', 'installed', 'installing', 'uninstall',
        'configure', 'configuration', 'configured', 'configuring',
        'build', 'builds', 'building', 'built', 'builder',
        'test', 'tests', 'testing', 'tested', 'tester',
        'run', 'runs', 'running', 'ran', 'runner',
        'create', 'creates', 'creating', 'created', 'creator', 'creation',
        'update', 'updates', 'updating', 'updated',
        'add', 'adds', 'adding', 'added', 'addition', 'additional',
        'remove', 'removes', 'removing', 'removed', 'removal',
        'delete', 'deletes', 'deleting', 'deleted', 'deletion',
        'modify', 'modifies', 'modifying', 'modified', 'modification',
        'change', 'changes', 'changing', 'changed',
        'implement', 'implements', 'implementing', 'implemented', 'implementation',
        'feature', 'features', 'featured', 'functionality', 'functional',
        'support', 'supports', 'supporting', 'supported',
        'include', 'includes', 'including', 'included', 'inclusion',
        'provide', 'provides', 'providing', 'provided', 'provider',
        'enable', 'enables', 'enabling', 'enabled',
        'allow', 'allows', 'allowing', 'allowed',
        'require', 'requires', 'requiring', 'required', 'requirement', 'requirements',
        'depend', 'depends', 'depending', 'dependent', 'dependency', 'dependencies',
        'integrate', 'integrates', 'integrating', 'integrated', 'integration',
        'analyze', 'analyzes', 'analyzing', 'analyzed', 'analysis', 'analyzer',
        'scan', 'scans', 'scanning', 'scanned', 'scanner',
        'export', 'exports', 'exporting', 'exported', 'exporter',
        'import', 'imports', 'importing', 'imported', 'importer',
        'process', 'processes', 'processing', 'processed', 'processor',
        'parse', 'parses', 'parsing', 'parsed', 'parser',
        'validate', 'validates', 'validating', 'validated', 'validation', 'validator',
        'check', 'checks', 'checking', 'checked', 'checker',
        'detect', 'detects', 'detecting', 'detected', 'detection', 'detector',
        'file', 'files', 'folder', 'folders', 'directory', 'directories',
        'path', 'paths', 'location', 'locations',
        'repository', 'repositories', 'repo', 'repos',
        'project', 'projects', 'package', 'packages', 'module', 'modules',
        'library', 'libraries', 'framework', 'frameworks',
        'version', 'versions', 'versioning', 'versioned',
        'release', 'releases', 'released', 'releasing',
        'commit', 'commits', 'committed', 'committing',
        'branch', 'branches', 'branching', 'branched',
        'merge', 'merges', 'merging', 'merged',
        'pull', 'push', 'fetch', 'clone', 'cloning', 'cloned',
        'code', 'codes', 'coding', 'coded', 'coder',
        'source', 'sources', 'script', 'scripts', 'program', 'programs',
        'application', 'applications', 'app', 'apps',
        'user', 'users', 'username', 'usernames',
        'password', 'passwords', 'token', 'tokens', 'key', 'keys',
        'access', 'accesses', 'accessing', 'accessed',
        'authenticate', 'authenticates', 'authenticating', 'authenticated', 'authentication',
        'authorize', 'authorizes', 'authorizing', 'authorized', 'authorization',
        'permission', 'permissions', 'privilege', 'privileges',
        'secure', 'secures', 'securing', 'secured', 'security',
        'private', 'public', 'protected', 'internal', 'external',
        'local', 'remote', 'global', 'static', 'dynamic',
        'automatic', 'automatically', 'manual', 'manually',
        'simple', 'simply', 'complex', 'complexity',
        'easy', 'easier', 'easiest', 'easily', 'difficult', 'difficulty',
        'quick', 'quickly', 'fast', 'faster', 'fastest', 'slow', 'slower', 'slowest',
        'small', 'smaller', 'smallest', 'large', 'larger', 'largest',
        'full', 'fully', 'partial', 'partially', 'complete', 'completely', 'incomplete',
        'multiple', 'single', 'many', 'few', 'several', 'various',
        'example', 'examples', 'sample', 'samples', 'demo', 'demos', 'demonstration',
        'basic', 'basics', 'advanced', 'standard', 'custom', 'default',
        'option', 'options', 'optional', 'setting', 'settings',
        'value', 'values', 'variable', 'variables', 'constant', 'constants',
        'type', 'types', 'kind', 'kinds', 'format', 'formats', 'formatted', 'formatting',
        'output', 'outputs', 'input', 'inputs', 'result', 'results',
        'data', 'information', 'content', 'contents',
        'message', 'messages', 'text', 'texts', 'string', 'strings',
        'number', 'numbers', 'numeric', 'numerical',
        'boolean', 'true', 'false', 'null', 'undefined', 'none',
        'empty', 'full', 'blank', 'filled',
        'start', 'starts', 'starting', 'started', 'stop', 'stops', 'stopping', 'stopped',
        'begin', 'begins', 'beginning', 'began', 'end', 'ends', 'ending', 'ended',
        'open', 'opens', 'opening', 'opened', 'close', 'closes', 'closing', 'closed',
        'read', 'reads', 'reading', 'write', 'writes', 'writing', 'written',
        'load', 'loads', 'loading', 'loaded', 'save', 'saves', 'saving', 'saved',
        'download', 'downloads', 'downloading', 'downloaded',
        'upload', 'uploads', 'uploading', 'uploaded',
        'send', 'sends', 'sending', 'sent', 'receive', 'receives', 'receiving', 'received',
        'request', 'requests', 'requesting', 'requested',
        'response', 'responses', 'responding', 'responded',
        'error', 'errors', 'warning', 'warnings', 'exception', 'exceptions',
        'debug', 'debugs', 'debugging', 'debugged', 'debugger',
        'log', 'logs', 'logging', 'logged', 'logger',
        'print', 'prints', 'printing', 'printed',
        'display', 'displays', 'displaying', 'displayed',
        'show', 'shows', 'showing', 'showed', 'shown',
        'hide', 'hides', 'hiding', 'hidden',
        'visible', 'visibility', 'invisible',
        'available', 'unavailable', 'availability',
        'enabled', 'disabled', 'enable', 'disable',
        'active', 'inactive', 'activate', 'deactivate',
        'valid', 'invalid', 'validate', 'validation',
        'correct', 'incorrect', 'proper', 'improper',
        'success', 'successful', 'successfully', 'fail', 'failed', 'failure',
        'pass', 'passed', 'passing', 'fail', 'failed', 'failing',
        'possible', 'impossible', 'possibly', 'probability',
        'necessary', 'unnecessary', 'optional', 'required',
        'recommended', 'suggestion', 'suggestions',
        'help', 'helps', 'helping', 'helped', 'helper',
        'describe', 'describes', 'describing', 'described', 'description',
        'explain', 'explains', 'explaining', 'explained', 'explanation',
        'specify', 'specifies', 'specifying', 'specified', 'specification',
        'define', 'defines', 'defining', 'defined', 'definition',
        'set', 'sets', 'setting', 'unset',
        'list', 'lists', 'listing', 'listed',
        'view', 'views', 'viewing', 'viewed', 'viewer',
        'edit', 'edits', 'editing', 'edited', 'editor',
        'search', 'searches', 'searching', 'searched',
        'find', 'finds', 'finding', 'found',
        'filter', 'filters', 'filtering', 'filtered',
        'sort', 'sorts', 'sorting', 'sorted',
        'group', 'groups', 'grouping', 'grouped',
        'organize', 'organizes', 'organizing', 'organized', 'organization',
        'manage', 'manages', 'managing', 'managed', 'manager', 'management',
        'control', 'controls', 'controlling', 'controlled', 'controller',
        'handle', 'handles', 'handling', 'handled', 'handler',
        'execute', 'executes', 'executing', 'executed', 'execution',
        'perform', 'performs', 'performing', 'performed', 'performance',
        'operate', 'operates', 'operating', 'operated', 'operation', 'operations',
        'function', 'functions', 'functioning', 'functioned',
        'method', 'methods', 'procedure', 'procedures',
        'algorithm', 'algorithms', 'logic', 'logical',
        'structure', 'structures', 'structured', 'structuring',
        'architecture', 'architectural', 'design', 'designs', 'designed', 'designing',
        'pattern', 'patterns', 'template', 'templates',
        'model', 'models', 'modeling', 'modeled',
        'schema', 'schemas', 'specification', 'specifications',
        'interface', 'interfaces', 'protocol', 'protocols',
        'connection', 'connections', 'connect', 'connecting', 'connected',
        'network', 'networks', 'networking', 'networked',
        'server', 'servers', 'client', 'clients',
        'service', 'services', 'daemon', 'daemons',
        'endpoint', 'endpoints', 'route', 'routes', 'routing', 'routed',
        'resource', 'resources', 'asset', 'assets',
        'component', 'components', 'element', 'elements',
        'property', 'properties', 'attribute', 'attributes',
        'field', 'fields', 'column', 'columns', 'row', 'rows',
        'table', 'tables', 'database', 'databases',
        'query', 'queries', 'querying', 'queried',
        'record', 'records', 'entry', 'entries',
        'item', 'items', 'object', 'objects',
        'collection', 'collections', 'array', 'arrays',
        'container', 'containers', 'wrapper', 'wrappers',
        'reference', 'references', 'referencing', 'referenced',
        'pointer', 'pointers', 'link', 'links', 'linking', 'linked',
        'bind', 'binds', 'binding', 'bound',
        'inherit', 'inherits', 'inheriting', 'inherited', 'inheritance',
        'extend', 'extends', 'extending', 'extended', 'extension', 'extensions',
        'override', 'overrides', 'overriding', 'overridden',
        'implement', 'implements', 'implementing', 'implemented', 'implementation',
    }
    
    def __init__(self, custom_dictionary: Optional[Set[str]] = None):
        """
        Initialize spell checker.
        
        Args:
            custom_dictionary: Optional set of additional words to consider correct
        """
        self.dictionary = self.COMMON_WORDS | self.TECHNICAL_TERMS
        if custom_dictionary:
            self.dictionary = self.dictionary | custom_dictionary
        self.logger = logging.getLogger('accudoc.spellcheck')
    
    def _extract_words(self, text: str) -> List[Tuple[str, int, int]]:
        """
        Extract words from text with their positions.
        
        Args:
            text: Text to extract words from
            
        Returns:
            List of (word, line_number, column) tuples
        """
        words = []
        for line_num, line in enumerate(text.split('\n'), 1):
            # Skip code blocks and inline code
            if '```' in line or line.strip().startswith('    '):
                continue
            
            # Remove inline code
            line = re.sub(r'`[^`]+`', '', line)
            
            # Remove URLs
            line = re.sub(r'https?://[^\s]+', '', line)
            
            # Remove markdown formatting
            line = re.sub(r'[*_#\[\]()]', ' ', line)
            
            # Extract words
            for match in re.finditer(r'\b[a-zA-Z]+\b', line):
                word = match.group().lower()
                col = match.start()
                words.append((word, line_num, col))
        
        return words
    
    def check_text(self, text: str) -> Dict[str, List[Dict[str, Any]]]:
        """
        Check text for spelling errors.
        
        Args:
            text: Text to check
            
        Returns:
            Dictionary with 'errors' list containing potential misspellings
        """
        words = self._extract_words(text)
        errors = []
        
        for word, line_num, col in words:
            # Skip very short words (likely abbreviations)
            if len(word) <= 2:
                continue
            
            # Skip words with numbers
            if any(c.isdigit() for c in word):
                continue
            
            # Check if word is in dictionary
            if word not in self.dictionary:
                errors.append({
                    'word': word,
                    'line': line_num,
                    'column': col,
                    'context': f"Line {line_num}"
                })
        
        return {'errors': errors, 'total_words': len(words), 'unique_errors': len(set(e['word'] for e in errors))}
    
    def check_file(self, filepath: Path) -> Dict[str, Any]:
        """
        Check a file for spelling errors.
        
        Args:
            filepath: Path to file to check
            
        Returns:
            Dictionary with check results
        """
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            result = self.check_text(content)
            result['file'] = str(filepath)
            return result
        except Exception as e:
            self.logger.error(f"Error checking file {filepath}: {e}")
            return {'file': str(filepath), 'errors': [], 'error': str(e)}
    
    def check_directory(self, dirpath: Path, extensions: List[str] = None) -> List[Dict[str, Any]]:
        """
        Check all documentation files in a directory.
        
        Args:
            dirpath: Directory to check
            extensions: File extensions to check (default: .md, .txt, .rst)
            
        Returns:
            List of check results for each file
        """
        if extensions is None:
            extensions = ['.md', '.txt', '.rst', '.markdown']
        
        results = []
        for ext in extensions:
            for filepath in dirpath.rglob(f'*{ext}'):
                result = self.check_file(filepath)
                if result.get('errors'):
                    results.append(result)
        
        return results
    
    def generate_report(self, results: List[Dict[str, Any]]) -> str:
        """
        Generate a spell check report.
        
        Args:
            results: Results from check_directory() or list of check_file() results
            
        Returns:
            Markdown formatted report
        """
        if not results:
            return "# Spell Check Report\n\n✅ No spelling issues found!"
        
        md = []
        md.append("# Spell Check Report\n")
        
        total_errors = sum(len(r.get('errors', [])) for r in results)
        total_files = len(results)
        
        md.append(f"**Files checked**: {total_files}")
        md.append(f"**Total potential issues**: {total_errors}\n")
        
        if total_errors == 0:
            md.append("✅ No spelling issues found!")
            return '\n'.join(md)
        
        # Group by file
        for result in results:
            filepath = result.get('file', 'Unknown')
            errors = result.get('errors', [])
            
            if not errors:
                continue
            
            md.append(f"## {filepath}\n")
            md.append(f"**Potential issues**: {len(errors)}\n")
            
            # Group errors by word
            word_occurrences = defaultdict(list)
            for error in errors:
                word_occurrences[error['word']].append(error['line'])
            
            md.append("| Word | Occurrences | Lines |")
            md.append("|------|-------------|-------|")
            for word in sorted(word_occurrences.keys()):
                lines = word_occurrences[word]
                line_str = ', '.join(str(l) for l in sorted(set(lines))[:5])
                if len(lines) > 5:
                    line_str += f", ... (+{len(lines) - 5} more)"
                md.append(f"| {word} | {len(lines)} | {line_str} |")
            md.append("")
        
        md.append("## Notes\n")
        md.append("- This is a basic spell checker and may flag technical terms or proper nouns")
        md.append("- Review flagged words to determine if they are actual errors")
        md.append("- Consider adding project-specific terms to a custom dictionary")
        md.append("- Code blocks and inline code are automatically skipped\n")
        
        return '\n'.join(md)
